//===- RISCVIMEDialect.h - RISCVIME dialect declaration ---------*- C++ -*-===//

#ifndef MLIR_DIALECT_RISCVIME_RISCVIMEDIALECT_H
#define MLIR_DIALECT_RISCVIME_RISCVIMEDIALECT_H

#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
// Required for Op B (LLVM_AnyVector types)
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMTypes.h"
// Generated by add_mlir_dialect(RISCVIME riscv_ime)
#include "mlir/Dialect/RISCVIME/RISCVIMEDialect.h.inc"

#define GET_OP_CLASSES
#include "mlir/Dialect/RISCVIME/RISCVIME.h.inc"

#endif // MLIR_DIALECT_RISCVIME_RISCVIMEDIALECT_H