; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: sed 's/iXLen/i64/g' %s | llc -mtriple=riscv64 -mattr=+zve64x,+xsmtvdot \
; RUN:   -verify-machineinstrs | FileCheck %s

define <vscale x 2 x i32> @vmadot(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3) {
; CHECK-LABEL: vmadot:
; CHECK:       vsetvli zero, a0, e32, m1, tu, ma
; CHECK:       smt.vmadot v8, v9, v10
  %a = call <vscale x 2 x i32> @llvm.riscv.vmadot.nxv2i32.nxv8i8.nxv8i8(
      <vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3, iXLen 2)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @vmadotu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3) {
; CHECK-LABEL: vmadotu:
; CHECK:       smt.vmadotu v8, v9, v10
  %a = call <vscale x 2 x i32> @llvm.riscv.vmadotu.nxv2i32.nxv8i8.nxv8i8(
      <vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3, iXLen 2)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @vmadotus(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3) {
; CHECK-LABEL: vmadotus:
; CHECK:       smt.vmadotus v8, v9, v10
  %a = call <vscale x 2 x i32> @llvm.riscv.vmadotus.nxv2i32.nxv8i8.nxv8i8(
      <vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3, iXLen 2)
  ret <vscale x 2 x i32> %a
}

define <vscale x 2 x i32> @vmadotsu(<vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3) {
; CHECK-LABEL: vmadotsu:
; CHECK:       smt.vmadotsu v8, v9, v10
  %a = call <vscale x 2 x i32> @llvm.riscv.vmadotsu.nxv2i32.nxv8i8.nxv8i8(
      <vscale x 2 x i32> %0, <vscale x 8 x i8> %1, <vscale x 8 x i8> %2, iXLen %3, iXLen 2)
  ret <vscale x 2 x i32> %a
}

declare <vscale x 2 x i32> @llvm.riscv.vmadot.nxv2i32.nxv8i8.nxv8i8(<vscale x 2 x i32>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen, iXLen)
declare <vscale x 2 x i32> @llvm.riscv.vmadotu.nxv2i32.nxv8i8.nxv8i8(<vscale x 2 x i32>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen, iXLen)
declare <vscale x 2 x i32> @llvm.riscv.vmadotus.nxv2i32.nxv8i8.nxv8i8(<vscale x 2 x i32>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen, iXLen)
declare <vscale x 2 x i32> @llvm.riscv.vmadotsu.nxv2i32.nxv8i8.nxv8i8(<vscale x 2 x i32>, <vscale x 8 x i8>, <vscale x 8 x i8>, iXLen, iXLen)
